### PR TITLE
Add lets encrypt example

### PR DESCRIPTION
**Pull request by scanon**
This uses a let's encrypt helper image to have a Let's Encrypt SSL proxy for a backend service.

### CODE REVIEW

**Comment by weaverba137** [comment]
Please include the Dockerfile and any auxiliary files used to create the image.

**Comment by weaverba137** [comment]
Also, based on a preliminary test, it looks like `web-lets` needs
```yaml
cap_drop:
     - ALL
```

**Comment by weaverba137** [comment]
I'm starting to hear from other people in my project who want to implement https on other stacks, so I'd like to get a working demonstration for them soon.  Are there still outstanding issues with this implementation or does it just need to be merged?  Please note my previous question about `cap_drop`.

**Comment by scanon** [comment]
Thanks for the note on cap_drop.  I have "extra powers" in spin and I often forget this.  Let me add that and we can merge it.

**Comment by scanon** [comment]
I think I've resolved all the comments.  So I'm going to merge it.

**Pull request merged**
